version: '3.8'
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    container_name: bimanager-database
    environment:
      MSSQL_SA_PASSWORD: password123@
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
